### ISSUE TITLE
SolrBundle: Migrate Solarium configuration to support Solr Cloud (K8S)

### ISSUE THREAD

**Issue by ambroisemaupate** [roadiz/core-bundle-dev-app#71]
- [x] Migrate docker compose to use Solr Cloud (ZooKeeper)

```yaml
    solr:
        image: solr:9-slim
        volumes:
            - solr:/var/solr
        environment:
            ZK_HOST: "zookeeper:2181"
        depends_on: [zookeeper]

    zookeeper:
        image: pravega/zookeeper:0.2.14
        volumes:
            - zookeeper-data:/data
            - zookeeper-datalog:/datalog
            - zookeeper-logs:/logs
        environment:
            ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
```

- [x] Migrate file based schema to CLI to create Solr _collection_ and custom fields
- [x] `bin/console solr:init`
- [x] `bin/console solr:drop`
